dist: xenial
language: python
cache: pip
matrix:
  include:
    - python: 3.10
      env: TOXENV=py310-pytesttrunk
    - python: 3.10
      env: TOXENV=py310-xdist
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: 3.10
      env: TOXENV=py310
    - python: pypy3
      env: TOXENV=pypy3
install:
  - pip install tox
script:
  - tox -e $TOXENV
